import { prepareModal } from './modal-system.js'
﻿const languages=['English','简体中文','한국어','日本語','Tiếng Việt','বাংলা','Filipino']
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
let rows=[{id:1,names:['TypeOne','','','','','','']}]
try{const cached=JSON.parse(localStorage.getItem('bo-activity-types-v1'));if(Array.isArray(cached)&&cached.length<=12&&cached.every(row=>Number.isFinite(row.id)&&Array.isArray(row.names)&&row.names.length===7&&row.names.every(name=>typeof name==='string')))rows=cached}catch{}
let order=null,notice='',dragged=null
const button=(label,cls,action,disabled=false)=>`<button type="button" class="semantic-btn ${cls}" data-type-action="${action}" ${disabled?'disabled':''}>${label}</button>`
export function renderActivityTypes(){const list=order||rows;return `<section class="settings-card activity-types"><div class="settings-card-heading"><h2>活動類型</h2></div><div class="activity-type-toolbar"><div>${button('＋ 新增分類','btn-add','add',!!order||rows.length>=12)}<span class="activity-type-count">已建立 <strong>${rows.length} / 12</strong> 個分類</span></div><div>${order?button('取消','btn-neutral','cancel')+button('儲存排序','btn-search','save-order'):button('↕ 排序','btn-edit','sort',rows.length<2)}</div></div>${order?'<p class="activity-type-hint">拖曳資料列調整順序，或使用上移／下移按鈕。</p>':''}<div class="activity-type-feedback" role="status">${escape(notice)}</div><div class="activity-type-scroll"><table class="activity-type-table"><thead><tr>${order?'<th class="activity-type-order">順序</th>':''}${languages.map(lang=>`<th>${lang}</th>`).join('')}<th class="activity-type-actions">操作</th></tr></thead><tbody>${list.map((row,index)=>`<tr data-type-id="${row.id}" ${order?'draggable="true"':''}>${order?`<td class="activity-type-order">⠿ ${index+1}</td>`:''}${row.names.map(name=>`<td>${name?escape(name):'<span class="activity-type-missing">—</span>'}</td>`).join('')}<td class="activity-type-actions"><div>${order?button('↑ 上移','btn-edit','up',index===0)+button('↓ 下移','btn-edit','down',index===list.length-1):button('✎ 編輯','btn-edit','edit')+button('× 刪除','btn-danger','delete')}</div></td></tr>`).join('')||'<tr><td colspan="8" class="activity-type-empty">尚未建立分類，點擊「新增分類」開始新增。</td></tr>'}</tbody></table></div></section>`}
function redraw(){const root=document.querySelector('.activity-types');if(root)root.outerHTML=renderActivityTypes()}
function persist(next){try{localStorage.setItem('bo-activity-types-v1',JSON.stringify(next));rows=next;return true}catch{notice='無法儲存，請稍後再試。';return false}}
function openEditor(row,trigger,deleting=false){const dialog=document.createElement('dialog');dialog.className='activity-type-dialog';dialog.setAttribute('aria-labelledby','activity-type-dialog-title');dialog.innerHTML=`<form><header><h2 id="activity-type-dialog-title">${deleting?'刪除分類':row?'編輯分類':'新增分類'}</h2></header><div class="activity-type-dialog-body">${deleting?`<p>確定刪除「<strong>${escape(row.names[0])}</strong>」？</p><p>刪除後將無法復原。</p>`:`<div class="activity-type-fields">${languages.map((lang,index)=>`<label>${lang}${index===0?' <span>（必填）</span>':''}<input class="control" name="language${index}" value="${escape(row?.names[index]||'')}" maxlength="80" ${index===0?'required':''}></label>`).join('')}</div>`}<p class="settings-error" role="alert"></p></div><footer>${button('取消','btn-neutral','close')}<button type="submit" class="semantic-btn ${deleting?'btn-danger':'btn-search'}">${deleting?'確認刪除':'儲存'}</button></footer></form>`;dialog.querySelector('[data-type-action="close"]').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{dialog.remove();if(trigger.isConnected)trigger.focus();else document.querySelector('[data-type-action="add"]')?.focus()},{once:true});dialog.querySelector('form').onsubmit=event=>{event.preventDefault();let next;if(deleting)next=rows.filter(item=>item.id!==row.id);else{const names=languages.map((_,index)=>dialog.querySelector(`[name="language${index}"]`).value.trim());if(!names[0]){dialog.querySelector('.settings-error').textContent='請填寫 English 分類名稱。';return}if(rows.some(item=>item.id!==row?.id&&item.names[0].toLowerCase()===names[0].toLowerCase())){dialog.querySelector('.settings-error').textContent='分類名稱已存在。';return}if(!row&&rows.length>=12)return;const updated={id:row?.id||Date.now(),names};next=row?rows.map(item=>item.id===row.id?updated:item):[...rows,updated]}if(!persist(next)){dialog.querySelector('.settings-error').textContent=notice;return}notice=deleting?'已刪除分類。':row?'已更新分類。':'已新增分類。';redraw();dialog.close()};prepareModal(dialog);document.body.append(dialog);dialog.showModal()}
document.addEventListener('click',event=>{const target=event.target.closest('.activity-types [data-type-action]');if(!target)return;const action=target.dataset.typeAction;const id=Number(target.closest('[data-type-id]')?.dataset.typeId);const row=rows.find(item=>item.id===id);if(action==='add'||action==='edit'||action==='delete'){openEditor(action==='add'?null:row,target,action==='delete');return}notice='';if(action==='sort')order=rows.map(row=>({...row}));if(action==='cancel')order=null;if(action==='save-order'&&persist(order)){order=null;notice='已儲存排序。'}if(action==='up'||action==='down'){const index=order.findIndex(row=>row.id===id),next=index+(action==='up'?-1:1);if(next>=0&&next<order.length)[order[index],order[next]]=[order[next],order[index]]}redraw()})
document.addEventListener('dragstart',event=>{const row=event.target.closest('.activity-types tr[draggable]');if(!row)return;dragged=Number(row.dataset.typeId);event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',String(dragged))})
document.addEventListener('dragover',event=>{if(order&&event.target.closest('.activity-types tr[draggable]'))event.preventDefault()})
document.addEventListener('drop',event=>{const target=event.target.closest('.activity-types tr[draggable]');if(!target||!order||dragged===null)return;event.preventDefault();const from=order.findIndex(row=>row.id===dragged),to=order.findIndex(row=>row.id===Number(target.dataset.typeId));if(from>=0&&to>=0){order.splice(to,0,order.splice(from,1)[0]);redraw()}dragged=null})
document.addEventListener('dragend',()=>{dragged=null})
