import './settings-demo.css'
const defaults = { transferEnabled: true, transferRule: 'passed', depositEnabled: true, limitEnabled: true, pendingLimit: 3, minDeposit: 100, maxDeposit: 50000, notifyEnabled: true, notifyChannel: 'inbox', notifyThreshold: 10000 }
Object.assign(defaults, { siteTitle:'101 BEST', supportEmail:'', serviceHours:'09:00–18:00', contactName:'', settingNotes:'' })
const promotions = [
 {id:1,title:'新會員首存優惠',type:'新會員優惠',start:'2026-09-01',end:'2026-09-30',state:'上架中'},
 {id:2,title:'週末存款加碼',type:'存款優惠',start:'2026-09-19',end:'2026-09-20',state:'排程中'},
 {id:3,title:'八月會員回饋',type:'會員回饋',start:'2026-08-01',end:'2026-08-31',state:'已下架'}
]
for(const row of promotions){defaults['promoTitle'+row.id]=row.title;defaults['promoState'+row.id]=row.state}
let promotionFilter='全部'
const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const storageKey = 'bo-settings-demo-v1'
let saved = { ...defaults }
try { const cached = JSON.parse(localStorage.getItem(storageKey)); if(cached && typeof cached === 'object') for(const key of Object.keys(defaults)) if(typeof cached[key] === typeof defaults[key]) saved[key] = cached[key] } catch {}
let draft = { ...saved }, active = 'transfer', message = ''
const tabs = [['transfer','轉點設定'],['deposit','存款設定'],['notify','通知設定'],['inputs','基本資料設定'],['promotions','優惠活動設定']]
const dirty = () => JSON.stringify(draft) !== JSON.stringify(saved)
const toggle = (key, label, description, disabled=false) => `<div class="settings-row"><div><label for="setting-${key}">${label}</label></div><label class="settings-switch"><input id="setting-${key}" data-setting="${key}" type="checkbox" ${draft[key]?'checked':''} ${disabled?'disabled':''}><span aria-hidden="true"></span></label></div>`
const radio = (key, val, title, text, disabled=false) => `<label class="settings-choice ${draft[key]===val?'is-selected':''}"><input type="radio" name="${key}" data-setting="${key}" value="${val}" ${draft[key]===val?'checked':''} ${disabled?'disabled':''}><span><strong>${title}</strong><small>${text}</small></span></label>`
const number = (key, title, unit, help, disabled=false) => `<div class="settings-field"><label for="setting-${key}">${title}</label><div class="settings-unit"><input id="setting-${key}" data-setting="${key}" type="number" min="${key==='pendingLimit'?1:0}" ${key==='pendingLimit'?'max="100"':''} step="1" value="${draft[key]}" ${disabled?'disabled':''} aria-describedby="help-${key} error-${key}"><span>${unit}</span></div><small id="help-${key}">${help}</small><span class="settings-error" id="error-${key}" data-error="${key}"></span></div>`
const textField=(key,label,type='text')=>`<div class="settings-field"><label for="setting-${key}">${label}</label><input class="control" id="setting-${key}" data-setting="${key}" type="${type}" value="${escapeHtml(draft[key])}"><span class="settings-error" data-error="${key}" id="error-${key}"></span></div>`
function panel() {
 if(active==='inputs')return `<section class="settings-card"><div class="settings-card-heading"><h2>基本資料</h2></div><div class="settings-fields settings-input-section">${textField('siteTitle','網站名稱')}${textField('contactName','聯絡人')}${textField('supportEmail','客服信箱','email')}${textField('serviceHours','客服時間')}</div><div class="settings-divider" role="separator"></div><div class="settings-field"><label for="setting-settingNotes">備註</label><textarea class="control" id="setting-settingNotes" data-setting="settingNotes" rows="3" maxlength="500">${escapeHtml(draft.settingNotes)}</textarea></div></section>`
 if(active==='promotions')return `<section class="settings-card"><div class="settings-card-heading"><h2>優惠活動</h2></div><div class="settings-promotion-filters" aria-label="活動狀態">${['全部','上架中','排程中','已下架'].map(state=>`<button type="button" data-promotion-filter="${state}" aria-pressed="${promotionFilter===state}" class="${promotionFilter===state?'is-active':''}">${state}</button>`).join('')}</div><div class="settings-promotion-wrap"><table class="settings-promotion-table"><thead><tr><th>活動名稱</th><th>活動類型</th><th>開始日期</th><th>結束日期</th><th>最後更新人員</th><th>狀態</th></tr></thead><tbody>${promotions.filter(row=>promotionFilter==='全部'||draft['promoState'+row.id]===promotionFilter).map(row=>`<tr><td data-label="活動名稱"><input class="control" aria-label="活動名稱 ${row.id}" data-setting="promoTitle${row.id}" value="${escapeHtml(draft['promoTitle'+row.id])}"></td><td data-label="活動類型">${row.type}</td><td data-label="開始日期">${row.start}</td><td data-label="結束日期">${row.end}</td><td data-label="最後更新人員">Peggy</td><td data-label="狀態"><select class="control guide-select" aria-label="活動狀態 ${row.id}" data-setting="promoState${row.id}">${['上架中','排程中','已下架'].map(state=>`<option ${draft['promoState'+row.id]===state?'selected':''}>${state}</option>`).join('')}</select></td></tr>`).join('') || '<tr><td colspan="6">沒有符合條件的活動</td></tr>'}</tbody></table></div></section>`

 if(active==='transfer') return `<section class="settings-card"><div class="settings-card-heading"><div><h2>轉點規則</h2></div></div>${toggle('transferEnabled','開放會員轉點','關閉後暫停會員轉點，原有設定仍會保留。')}<div class="settings-divider" role="separator"></div><fieldset class="settings-group" ${draft.transferEnabled?'':'disabled'}><legend>允許轉點的條件</legend><div class="settings-choices">${radio('transferRule','passed','通過稽核後可轉點','會員需完成稽核條件，才可進行轉點。')}${radio('transferRule','all','不限制稽核狀態','會員尚未通過稽核時，也允許進行轉點。')}</div></fieldset>${!draft.transferEnabled?'<p class="settings-note">轉點已關閉；重新開啟後可調整下方條件。</p>':''}</section>`
 if(active==='deposit') return `<section class="settings-card"><div class="settings-card-heading"><div><h2>存款限制</h2></div></div>${toggle('depositEnabled','開放會員存款','關閉時保留限制設定，重新開啟即可繼續使用。')}<div class="settings-divider" role="separator"></div>${toggle('limitEnabled','限制待處理存款筆數','避免同一會員同時建立過多待處理申請。',!draft.depositEnabled)}<div class="settings-fields">${number('pendingLimit','待處理筆數上限','筆','可設定 1–100 筆。',!draft.depositEnabled||!draft.limitEnabled)}</div><div class="settings-divider"></div><h3>單筆存款金額</h3><div class="settings-fields">${number('minDeposit','最低金額','TWD','每筆存款可接受的最低金額。',!draft.depositEnabled)}${number('maxDeposit','最高金額','TWD','不得低於最低金額。',!draft.depositEnabled)}</div></section>`
 return `<section class="settings-card"><div class="settings-card-heading"><div><h2>作業通知</h2></div></div>${toggle('notifyEnabled','接收大額存款通知','存款達到設定金額時，通知後台管理人員。')}<div class="settings-divider" role="separator"></div><fieldset class="settings-group" ${draft.notifyEnabled?'':'disabled'}><legend>接收方式</legend><div class="settings-choices">${radio('notifyChannel','inbox','站內通知','在後台通知中心查看作業提醒。')}${radio('notifyChannel','both','站內通知與電子郵件','同時寄送至管理員已設定的電子郵件。')}</div></fieldset><div class="settings-divider" role="separator"></div><div class="settings-fields">${number('notifyThreshold','通知金額門檻','TWD','單筆金額達到門檻時發送通知。',!draft.notifyEnabled)}</div></section>`
}
window.renderSettingsPage = () => `<div class="settings-demo"><div class="source-filter card settings-platform-filter"><div class="source-filter-grid"><div class="filter-field"><label>平台名稱</label><select class="control"><option>101 BEST</option></select></div></div></div><div class="settings-tabs" role="tablist" aria-label="設定分類">${tabs.map(([key,label])=>`<button type="button" role="tab" id="settings-tab-${key}" aria-controls="settings-panel" aria-selected="${key===active}" tabindex="${key===active?0:-1}" data-settings-tab="${key}" class="${active===key?'is-active':''}">${label}</button>`).join('')}</div><div id="settings-panel" role="tabpanel" aria-labelledby="settings-tab-${active}">${panel()}</div><footer class="settings-savebar"><div class="settings-save-status" role="status">${message || '儲存後才會套用'}</div><div class="settings-save-actions"><button type="button" class="semantic-btn btn-neutral" data-settings-cancel ${dirty()?'':'disabled'}>取消變更</button><button type="button" class="semantic-btn btn-search" data-settings-save ${dirty()?'':'disabled'}>儲存設定</button></div></footer></div>`
function redraw() { const page=document.querySelector('.page'); if(page?.querySelector('.settings-demo')) page.innerHTML=window.renderSettingsPage() }
function status() { message=''; const root=document.querySelector('.settings-demo'); if(!root)return; root.querySelector('.settings-save-status').textContent='儲存後才會套用';root.querySelector('[data-settings-save]').disabled=!dirty();root.querySelector('[data-settings-cancel]').disabled=!dirty() }
function validate() {
 const errors={}
 if(draft.depositEnabled){if(draft.limitEnabled&&(!Number.isInteger(draft.pendingLimit)||draft.pendingLimit<1||draft.pendingLimit>100))errors.pendingLimit='請輸入 1–100 的整數。';for(const key of ['minDeposit','maxDeposit'])if(!Number.isFinite(draft[key])||draft[key]<0)errors[key]='請輸入不小於 0 的金額。';if(draft.maxDeposit<draft.minDeposit)errors.maxDeposit='最高金額不可低於最低金額。'}
 if(draft.notifyEnabled&&(!Number.isFinite(draft.notifyThreshold)||draft.notifyThreshold<=0))errors.notifyThreshold='請輸入大於 0 的金額。'
 return errors
}
document.addEventListener('input',e=>{const input=e.target.closest('[data-setting]');if(!input||input.type==='checkbox'||input.type==='radio'||input.tagName==='SELECT')return;draft[input.dataset.setting]=input.type==='number'?(input.value===''?NaN:Number(input.value)):input.value;status();input.removeAttribute('aria-invalid');const err=document.querySelector(`[data-error="${input.dataset.setting}"]`);if(err)err.textContent=''})
document.addEventListener('change',e=>{const input=e.target.closest('[data-setting]');if(!input||!['checkbox','radio','select-one'].includes(input.type))return;draft[input.dataset.setting]=input.type==='checkbox'?input.checked:input.value;message='';const id=input.id;redraw();if(id)document.getElementById(id)?.focus()})
document.addEventListener('click',e=>{
 const filter=e.target.closest('[data-promotion-filter]');if(filter){promotionFilter=filter.dataset.promotionFilter;redraw();return}
 const tab=e.target.closest('[data-settings-tab]');if(tab){active=tab.dataset.settingsTab;message='';redraw();document.getElementById(`settings-tab-${active}`)?.focus();return}
 if(e.target.closest('[data-settings-cancel]')){draft={...saved};message='已取消變更';redraw()}
 if(e.target.closest('[data-settings-save]')){const errors=validate();const first=Object.keys(errors)[0];if(first){active=first==='notifyThreshold'?'notify':'deposit';redraw();for(const [key,text] of Object.entries(errors)){const error=document.querySelector(`[data-error="${key}"]`);if(error){error.textContent=text;document.getElementById(`setting-${key}`).setAttribute('aria-invalid','true')}}document.getElementById(`setting-${first}`)?.focus();return}try{localStorage.setItem(storageKey,JSON.stringify(draft));saved={...draft};message='✓ 設定已儲存';redraw()}catch{message='無法儲存，請稍後重試。';redraw()}}
})
document.addEventListener('keydown',e=>{const tab=e.target.closest('[data-settings-tab]');if(!tab||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const index=tabs.findIndex(([key])=>key===active);active=tabs[e.key==='Home'?0:e.key==='End'?tabs.length-1:(index+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length][0];redraw();document.getElementById(`settings-tab-${active}`)?.focus()})
document.addEventListener('click',e=>{if(!document.querySelector('.settings-demo')||!dirty())return;const navigation=e.target.closest('.nav-item[data-route-key], #quickTabs button');if(!navigation)return;const key=navigation.dataset.routeKey||navigation.dataset.page;if(key==='設定相關頁面'&&!e.target.closest('#quickTabs button span'))return;if(!confirm('有尚未儲存的設定。確定放棄變更並離開？')){e.preventDefault();e.stopImmediatePropagation()}else{draft={...saved};message=''}},true)
window.addEventListener('beforeunload',e=>{if(dirty()){e.preventDefault();e.returnValue=''}})

// Open the default page after its renderer and navigation handlers are ready.
document.querySelector('.nav-item[data-route-key="設定相關頁面"]')?.click()
